/* jshint node: true, esversion: 10, -W014, -W033 */
/* eslint-disable new-cap */
'use strict'

module.exports = {
  accNotFound: 'accessory not found',
  accNotReady: 'cannot currently be controlled, see plugin startup logs for any error',
  brand: 'Flume',
  cfgDef: 'is not a valid number so using default of',
  cfgDup: 'will be ignored since another entry with this ID already exists',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  complete: '✓ Setup complete',
  curHeat: 'current heating',
  curState: 'current state',
  curTarg: 'current target',
  curTemp: 'current temperature',
  devAdd: 'has been added to Homebridge',
  devInit: 'initialised with id',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRef: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devNotUpdated: 'could not be updated as',
  devRemove: 'has been removed from Homebridge',
  disabled: 'To change this, set disablePlugin to false',
  disableHTTP: 'Disabling HTTP client as',
  disabling: 'Disabling plugin',
  hbVersionFail: 'Your version of Homebridge is too low - please update to v1.3',
  httpRetry: 'Unable to reach Thermobit, retrying in 30 seconds',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  labelHeating: 'heating',
  labelIdle: 'idle',
  labelMan: 'manual',
  labelSch: 'schedule',
  noCreds: 'Thermobit username and/or password not configured',
  noDevices: 'no data received from Thermobit server whilst obtaining device list',
  noTokenExists: 'no Thermobit account token exists',
  pluginNotConf: 'Plugin has not been configured',
  receivingUpdate: 'receiving update',
  scheduleFailed: 'Program schedule could not be updated as',
  scheduleInvalid: 'Not updating program schedule as configuration is invalid or incomplete',
  scheduleUpdated: 'Program schedule successfully updated',
  syncFailed: 'Sync process failed as',
  updateFail: 'could not be updated as',
  zWelcome: [
    "Don't forget to ☆ this plugin on GitHub if you're finding it useful!",
    'Have a feature request? Visit https://bit.ly/hb-thermobit-issues to ask!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/bwp91',
    "Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW",
    'Thanks for using this plugin, I hope you find it helpful!',
    'This plugin has been made with ♥ by bwp91 from the UK!',
    'Check out my other Homebridge plugins! https://github.com/bwp91',
    'Have time to give this plugin a review? https://bit.ly/hb-thermobit-review',
    "This plugin needs it's first ☆ rating on HOOBS! https://bit.ly/hb-thermobit-review",
    'Want to see this plugin in your own language? Let me know!'
  ]
}
